language: node_js
sudo: false
node_js:
  - '10'
  - '12'
  - 'stable'
before_script:
  - npm install mocha
  - npm install superagent
  - npm install expect.js
  - npm install socket.io-client
  - npm install socket.io
script:
  - npm run test:mocha
git:
  depth: 1
cache:
  directories:
    - node_modules