language: node_js
sudo: false
node_js:
  - '10'
  - '12'
  - 'stable'
before_script:
  #- npm install nyc@latest --save-dev
  #- npm install mocha@latest --save-dev
  - npm install superagent --save-dev
  - npm install expect --save-dev
  - npm install socket.io-client --save-dev
  - npm install socket.io --save-dev
script:
  # npm run test:mocha
  # npm run lint
  # Run test script
  - npm run test:cov
  # Run linting
  - npm run lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info
git:
  depth: 1
cache:
  directories:
    - node_modules