platform:
  - x86
  - x64
environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "14"
install:
  # Install Node.js
  - ps: >-
      try { Install-Product node $env:nodejs_version $env:platform -ErrorAction Stop }
      catch { Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) }
  # Configure npm
  - ps: |
      # mocha for testing
      npm install superagent --save-dev
      npm install expect --save-dev
      npm install socket.io-client --save-dev
      npm install socket.io --save-dev
      npm install mocha --save-dev
  # Install Node.js modules
  - npm install
build: off
test_script:
  # Output version data
  - ps: |
      node --version
      npm --version
  # Run test script
  - npm run test:cov
  # Run linting
  - npm run lint
version: "{build}"
